### all reports

GET http://localhost:3000/reports


### create report

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"HONDA",
    "model":"AWQ",
    "year":1997,
    "mileage":100,
    "lng":0,
    "lat":0,
    "price":500000
}

### approve report
PATCH  http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved":true
}



### get estimate value

GET http://localhost:3000/reports/get-estimate?make=dfdf&model=asd&year=2020&mileage=22&lng=0&lat=0