### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"test@test1234.com",
    "password":"password"
}

### signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"test@info.com",
    "password":"password"
}

### Get auth user
GET http://localhost:3000/auth/user


### signout user
POST http://localhost:3000/auth/signout

### All users
GET http://localhost:3000/auth


### Find user by id
GET http://localhost:3000/auth/2

### Find user by email
GET http://localhost:3000/auth?email=test@test1234.com


### delete user
DELETE http://localhost:3000/auth/1


### update user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email":"test@info.com"
}